# Author: Ali Uneri
# Date: 2013-05-02

cmt_end_definition()
# -----------------------------------------------------------------------------

find_package(PythonInterp REQUIRED)
find_package(PythonLibs REQUIRED)
find_package(NumPy REQUIRED)

set(PYTHON_RELEASE_LIBRARY ${PYTHON_LIBRARY})
if(WIN32)
  list(GET PYTHON_LIBRARY 0 IS_OPTIMIZED)
  if(${IS_OPTIMIZED} STREQUAL "optimized")
    list(GET PYTHON_LIBRARY 1 PYTHON_RELEASE_LIBRARY)
  endif()
endif()

set(CMT_PYTHON_VERSION "${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}" CACHE INTERNAL "")
set(CMT_PYTHON_EXECUTABLE "${PYTHON_EXECUTABLE}" CACHE INTERNAL "")
set(CMT_PYTHON_INCLUDE_DIR "${PYTHON_INCLUDE_DIR}" CACHE INTERNAL "")
set(CMT_PYTHON_LIBRARY "${PYTHON_RELEASE_LIBRARY}" CACHE INTERNAL "")

ExternalProject_Add(${EP_NAME}
  DOWNLOAD_COMMAND ""
  CONFIGURE_COMMAND ""
  BUILD_COMMAND ""
  INSTALL_COMMAND "")
