language: cpp
compiler:
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test

notifications:
  recipients:
    - auneri@gmail.com
  email:
    on_success: change
    on_failure: always
