language: c

matrix:
  include:
    - os: linux
      sudo: false
    - os: linux
      dist: trusty
      sudo: false
    - os: osx

install:
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake -DCMakeAll_BUILD_TESTING:BOOL=ON ..

script:
  - make
  - make test ARGS="--extra-verbose"
