set(CMA_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(CMA_CMAKE_DIR "${CMA_SOURCE_DIR}/CMake")
set(CMA_PROJECTS_DIR "${CMA_SOURCE_DIR}/Projects")

include(CMakeDependentOption)
include(CMakeParseArguments)
include(ExternalProject)

list(APPEND CMAKE_MODULE_PATH "${CMA_CMAKE_DIR}")
include(cmaVariablesPrivate)
include(cmaVariables)
include(cmaMacrosPrivate)
include(cmaMacros)
include(cmaFunctionsPrivate)
include(cmaFunctions)
